title: XinyueZhang's Homepage
page-top-title: XinyueZhang
top-section-bg-text: Be what you wanna be
home-subtitle: XinyueZhang&ensp;|&ensp;章新悦
copyright-text: '&copy; XinyueZhang 2026. All Rights Reserved.'
